# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from database_service.models.base_model_ import Model
from database_service import util


class AssetMetadata(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, name: str=None, ticker: str=None, website: str=None, social_links: Dict[str, str]=None):  # noqa: E501
        """AssetMetadata - a model defined in Swagger

        :param id: The id of this AssetMetadata.  # noqa: E501
        :type id: int
        :param name: The name of this AssetMetadata.  # noqa: E501
        :type name: str
        :param ticker: The ticker of this AssetMetadata.  # noqa: E501
        :type ticker: str
        :param website: The website of this AssetMetadata.  # noqa: E501
        :type website: str
        :param social_links: The social_links of this AssetMetadata.  # noqa: E501
        :type social_links: Dict[str, str]
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'ticker': str,
            'website': str,
            'social_links': Dict[str, str]
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'ticker': 'ticker',
            'website': 'website',
            'social_links': 'social_links'
        }
        self._id = id
        self._name = name
        self._ticker = ticker
        self._website = website
        self._social_links = social_links

    @classmethod
    def from_dict(cls, dikt) -> 'AssetMetadata':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AssetMetadata of this AssetMetadata.  # noqa: E501
        :rtype: AssetMetadata
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this AssetMetadata.


        :return: The id of this AssetMetadata.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this AssetMetadata.


        :param id: The id of this AssetMetadata.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this AssetMetadata.


        :return: The name of this AssetMetadata.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this AssetMetadata.


        :param name: The name of this AssetMetadata.
        :type name: str
        """

        self._name = name

    @property
    def ticker(self) -> str:
        """Gets the ticker of this AssetMetadata.


        :return: The ticker of this AssetMetadata.
        :rtype: str
        """
        return self._ticker

    @ticker.setter
    def ticker(self, ticker: str):
        """Sets the ticker of this AssetMetadata.


        :param ticker: The ticker of this AssetMetadata.
        :type ticker: str
        """

        self._ticker = ticker

    @property
    def website(self) -> str:
        """Gets the website of this AssetMetadata.


        :return: The website of this AssetMetadata.
        :rtype: str
        """
        return self._website

    @website.setter
    def website(self, website: str):
        """Sets the website of this AssetMetadata.


        :param website: The website of this AssetMetadata.
        :type website: str
        """

        self._website = website

    @property
    def social_links(self) -> Dict[str, str]:
        """Gets the social_links of this AssetMetadata.


        :return: The social_links of this AssetMetadata.
        :rtype: Dict[str, str]
        """
        return self._social_links

    @social_links.setter
    def social_links(self, social_links: Dict[str, str]):
        """Sets the social_links of this AssetMetadata.


        :param social_links: The social_links of this AssetMetadata.
        :type social_links: Dict[str, str]
        """

        self._social_links = social_links
