# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from database_service.models.base_model_ import Model
from database_service.models.asset_metadata import AssetMetadata  # noqa: F401,E501
from database_service import util


class Assets(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self):  # noqa: E501
        """Assets - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'Assets':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Assets of this Assets.  # noqa: E501
        :rtype: Assets
        """
        return util.deserialize_model(dikt, cls)
