# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from database_service.models.base_model_ import Model
from database_service import util


class InlineResponse200Assets(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ticker: str=None, quantity: float=None):  # noqa: E501
        """InlineResponse200Assets - a model defined in Swagger

        :param ticker: The ticker of this InlineResponse200Assets.  # noqa: E501
        :type ticker: str
        :param quantity: The quantity of this InlineResponse200Assets.  # noqa: E501
        :type quantity: float
        """
        self.swagger_types = {
            'ticker': str,
            'quantity': float
        }

        self.attribute_map = {
            'ticker': 'ticker',
            'quantity': 'quantity'
        }
        self._ticker = ticker
        self._quantity = quantity

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200Assets':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_assets of this InlineResponse200Assets.  # noqa: E501
        :rtype: InlineResponse200Assets
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ticker(self) -> str:
        """Gets the ticker of this InlineResponse200Assets.


        :return: The ticker of this InlineResponse200Assets.
        :rtype: str
        """
        return self._ticker

    @ticker.setter
    def ticker(self, ticker: str):
        """Sets the ticker of this InlineResponse200Assets.


        :param ticker: The ticker of this InlineResponse200Assets.
        :type ticker: str
        """

        self._ticker = ticker

    @property
    def quantity(self) -> float:
        """Gets the quantity of this InlineResponse200Assets.


        :return: The quantity of this InlineResponse200Assets.
        :rtype: float
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: float):
        """Sets the quantity of this InlineResponse200Assets.


        :param quantity: The quantity of this InlineResponse200Assets.
        :type quantity: float
        """

        self._quantity = quantity
