# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from database_service.models.base_model_ import Model
from database_service import util


class InlineResponse2011(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None):  # noqa: E501
        """InlineResponse2011 - a model defined in Swagger

        :param id: The id of this InlineResponse2011.  # noqa: E501
        :type id: str
        """
        self.swagger_types = {
            'id': str
        }

        self.attribute_map = {
            'id': 'id'
        }
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2011':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_201_1 of this InlineResponse2011.  # noqa: E501
        :rtype: InlineResponse2011
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this InlineResponse2011.

        Autogenerated uuid for the order  # noqa: E501

        :return: The id of this InlineResponse2011.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this InlineResponse2011.

        Autogenerated uuid for the order  # noqa: E501

        :param id: The id of this InlineResponse2011.
        :type id: str
        """

        self._id = id
