# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from database_service.models.base_model_ import Model
from database_service import util


class InlineResponse201(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, timestamp: float=None):  # noqa: E501
        """InlineResponse201 - a model defined in Swagger

        :param timestamp: The timestamp of this InlineResponse201.  # noqa: E501
        :type timestamp: float
        """
        self.swagger_types = {
            'timestamp': float
        }

        self.attribute_map = {
            'timestamp': 'timestamp'
        }
        self._timestamp = timestamp

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse201':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_201 of this InlineResponse201.  # noqa: E501
        :rtype: InlineResponse201
        """
        return util.deserialize_model(dikt, cls)

    @property
    def timestamp(self) -> float:
        """Gets the timestamp of this InlineResponse201.

        Timestamp of the price data in milliseconds.  # noqa: E501

        :return: The timestamp of this InlineResponse201.
        :rtype: float
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: float):
        """Sets the timestamp of this InlineResponse201.

        Timestamp of the price data in milliseconds.  # noqa: E501

        :param timestamp: The timestamp of this InlineResponse201.
        :type timestamp: float
        """

        self._timestamp = timestamp
