version: '3'

services:
  app:
    container_name: app
    build: .
    image: blueflow/dev-app-1
    ports:
      - 5432
    depends_on:
    - postgresql


  postgresql:
    container_name: postgresql
    image: postgres
    restart: always
    ports:
    - 5432:5432
    expose:
    - 5432
    environment:
      POSTGRES_PASSWORD: 123123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - data:/var/lib/postgresql/data


volumes:
  data:
