# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from src.api.models.base_model_ import Model
from src.api import util


class InlineResponse201(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, timestamp=None):  # noqa: E501
        """InlineResponse201 - a model defined in OpenAPI

        :param timestamp: The timestamp of this InlineResponse201.  # noqa: E501
        :type timestamp: float
        """
        self.openapi_types = {
            'timestamp': float
        }

        self.attribute_map = {
            'timestamp': 'timestamp'
        }

        self._timestamp = timestamp

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse201':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_201 of this InlineResponse201.  # noqa: E501
        :rtype: InlineResponse201
        """
        return util.deserialize_model(dikt, cls)

    @property
    def timestamp(self):
        """Gets the timestamp of this InlineResponse201.

        Timestamp of the price data in milliseconds.  # noqa: E501

        :return: The timestamp of this InlineResponse201.
        :rtype: float
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this InlineResponse201.

        Timestamp of the price data in milliseconds.  # noqa: E501

        :param timestamp: The timestamp of this InlineResponse201.
        :type timestamp: float
        """

        self._timestamp = timestamp
