# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from src.api.models.base_model_ import Model
from src.api import util


class InlineResponse200Assets(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, ticker=None, quantity=None):  # noqa: E501
        """InlineResponse200Assets - a model defined in OpenAPI

        :param ticker: The ticker of this InlineResponse200Assets.  # noqa: E501
        :type ticker: str
        :param quantity: The quantity of this InlineResponse200Assets.  # noqa: E501
        :type quantity: float
        """
        self.openapi_types = {
            'ticker': str,
            'quantity': float
        }

        self.attribute_map = {
            'ticker': 'ticker',
            'quantity': 'quantity'
        }

        self._ticker = ticker
        self._quantity = quantity

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200Assets':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_assets of this InlineResponse200Assets.  # noqa: E501
        :rtype: InlineResponse200Assets
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ticker(self):
        """Gets the ticker of this InlineResponse200Assets.


        :return: The ticker of this InlineResponse200Assets.
        :rtype: str
        """
        return self._ticker

    @ticker.setter
    def ticker(self, ticker):
        """Sets the ticker of this InlineResponse200Assets.


        :param ticker: The ticker of this InlineResponse200Assets.
        :type ticker: str
        """

        self._ticker = ticker

    @property
    def quantity(self):
        """Gets the quantity of this InlineResponse200Assets.


        :return: The quantity of this InlineResponse200Assets.
        :rtype: float
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this InlineResponse200Assets.


        :param quantity: The quantity of this InlineResponse200Assets.
        :type quantity: float
        """

        self._quantity = quantity
