# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from src.api.models.base_model_ import Model
from src.api.models.order import Order
from src.api import util

from src.api.models.order import Order  # noqa: E501

class Orders(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, ticker=None):  # noqa: E501
        """Orders - a model defined in OpenAPI

        :param ticker: The ticker of this Orders.  # noqa: E501
        :type ticker: str
        """
        self.openapi_types = {
            'ticker': str
        }

        self.attribute_map = {
            'ticker': 'ticker'
        }

        self._ticker = ticker

    @classmethod
    def from_dict(cls, dikt) -> 'Orders':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Orders of this Orders.  # noqa: E501
        :rtype: Orders
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ticker(self):
        """Gets the ticker of this Orders.


        :return: The ticker of this Orders.
        :rtype: str
        """
        return self._ticker

    @ticker.setter
    def ticker(self, ticker):
        """Sets the ticker of this Orders.


        :param ticker: The ticker of this Orders.
        :type ticker: str
        """

        self._ticker = ticker
