# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from src.api.models.base_model_ import Model
from src.api.models.wallet_assets import WalletAssets
from src.api import util

from src.api.models.wallet_assets import WalletAssets  # noqa: E501

class Wallet(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, datetime=None, assets=None):  # noqa: E501
        """Wallet - a model defined in OpenAPI

        :param datetime: The datetime of this Wallet.  # noqa: E501
        :type datetime: datetime
        :param assets: The assets of this Wallet.  # noqa: E501
        :type assets: List[WalletAssets]
        """
        self.openapi_types = {
            'datetime': datetime,
            'assets': List[WalletAssets]
        }

        self.attribute_map = {
            'datetime': 'datetime',
            'assets': 'assets'
        }

        self._datetime = datetime
        self._assets = assets

    @classmethod
    def from_dict(cls, dikt) -> 'Wallet':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Wallet of this Wallet.  # noqa: E501
        :rtype: Wallet
        """
        return util.deserialize_model(dikt, cls)

    @property
    def datetime(self):
        """Gets the datetime of this Wallet.


        :return: The datetime of this Wallet.
        :rtype: datetime
        """
        return self._datetime

    @datetime.setter
    def datetime(self, datetime):
        """Sets the datetime of this Wallet.


        :param datetime: The datetime of this Wallet.
        :type datetime: datetime
        """

        self._datetime = datetime

    @property
    def assets(self):
        """Gets the assets of this Wallet.


        :return: The assets of this Wallet.
        :rtype: List[WalletAssets]
        """
        return self._assets

    @assets.setter
    def assets(self, assets):
        """Sets the assets of this Wallet.


        :param assets: The assets of this Wallet.
        :type assets: List[WalletAssets]
        """

        self._assets = assets
